name: Build

on: [push, pull_request]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup repo
        uses: actions/checkout@v2
      - name: Setup Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install Yarn
        run: npm install -g yarn
      - name: Run update.py
        run: python update.py
