name: OpenSOM consumer-example

on:
  push:
    paths:
      - "packages/consumer-example/**"
      - "packages/eslint-config/**"
      - ".github/workflows/consumer-example.yml"

jobs:
  ESLint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/consumer-example
    steps:
      - name: Setup repo
        uses: actions/checkout@v3
      - name: Setup Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Install PNPM
        uses: pnpm/action-setup@v2
        with:
          version: latest
          run_install: true
      - name: Run linter
        run: pnpm lint

  TypeScript:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/consumer-example
    steps:
      - name: Setup repo
        uses: actions/checkout@v3
      - name: Setup Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Install PNPM
        uses: pnpm/action-setup@v2
        with:
          version: latest
          run_install: true
      - name: Rename env
        run: cp .env.example .env
      - name: Run Type Checking
        run: pnpm tsc

  Deploy:
    runs-on: ubuntu-latest
    needs: [ESLint, TypeScript]
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Setup repo
        uses: actions/checkout@v3
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: opensom-consumer
          heroku_email: silash35@gmail.com
          dontautocreate: true
