name: OpenSOM Frontend

on:
  push:
    paths:
      - "packages/frontend/**"
      - ".github/workflows/frontend.yml"
      - "Dockerfile.frontend"
      - "package.json"

jobs:
  ESLint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/frontend
    steps:
      - name: Setup repo
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install PNPM
        uses: pnpm/action-setup@v2
        with:
          version: latest
          run_install: true
      - name: Run linter
        run: pnpm lint

  TypeScript:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/frontend
    steps:
      - name: Setup repo
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install PNPM
        uses: pnpm/action-setup@v2
        with:
          version: latest
          run_install: true
      - name: Run Type Checking
        run: pnpm tsc
  Deploy:
    if: github.ref == 'refs/heads/master'
    needs: [ESLint, TypeScript]
    runs-on: ubuntu-latest
    steps:
      - name: Setup repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Push to dokku
        uses: dokku/github-action@master
        with:
          git_remote_url: "ssh://dokku@168.138.240.103/opensom-frontend"
          ssh_private_key: ${{ secrets.DOKKU_DEPLOY_KEY }}
