name: OpenSOM Tracker

on:
  push:
    paths:
      - "packages/tracker/**"
      - "packages/config/**"
      - ".github/workflows/tracker.yml"
      - "Dockerfile.tracker"
      - "package.json"
      - pnpm-lock.yaml
jobs:
  ESLint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/tracker
    steps:
      - name: Setup repo
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install PNPM
        uses: pnpm/action-setup@v2
        with:
          version: latest
          run_install: true
      - name: Run linter
        run: pnpm lint

  TypeScript:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/tracker
    steps:
      - name: Setup repo
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install PNPM
        uses: pnpm/action-setup@v2
        with:
          version: latest
          run_install: true
      - name: Run Type Checking
        run: pnpm tsc

  Deploy:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - name: Setup repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Push to dokku
        uses: dokku/github-action@master
        with:
          git_remote_url: "ssh://dokku@168.138.240.103/opensom-tracker"
          ssh_private_key: ${{ secrets.DOKKU_DEPLOY_KEY }}
